## メモ
### 概要
以下の設定になっている際に、server/main.goで返すStatus Codeが502の時と503の時での挙動が意図通りになっているか確認する。
- 502の時はリトライを行う
- 503の時はリトライを行わない

```go: client/main.go
retryClient.CheckRetry = func(ctx context.Context, resp *http.Response, err error) (bool, error) {
		if resp.StatusCode == http.StatusServiceUnavailable {
			return false, nil
		}
		return retryablehttp.DefaultRetryPolicy(ctx, resp, err)
	}
```

### 結果
#### 502の場合
```bash
> go run main.go
2023/04/18 13:04:58 [DEBUG] GET http://localhost:8080
```

#### 503の場合
```bash
> go run main.go
2023/04/18 13:05:53 [DEBUG] GET http://localhost:8080
2023/04/18 13:05:53 [DEBUG] GET http://localhost:8080 (status: 502): retrying in 1s (4 left)
2023/04/18 13:05:54 [DEBUG] GET http://localhost:8080 (status: 502): retrying in 2s (3 left)
2023/04/18 13:05:56 [DEBUG] GET http://localhost:8080 (status: 502): retrying in 4s (2 left)
2023/04/18 13:06:00 [DEBUG] GET http://localhost:8080 (status: 502): retrying in 8s (1 left)
Get "http://localhost:8080": GET http://localhost:8080 giving up after 5 attempt(s)
```